name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Check formatting with Prettier
      run: yarn format:check
    - name: Check quality with ESLint
      run: yarn lint
    - name: Check types compile
      run: yarn type-check
    - name: Check unit tests pass
      run: yarn unit test
    - name: Check E2E tests pass
      run: yarn e2e test
    - name: Check app builds
      run: yarn build
